<?php

namespace Container5nyig5r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeyAnalyzerManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Jose\Component\KeyManagement\Analyzer\KeyAnalyzerManager' shared autowired service.
     *
     * @return \Jose\Component\KeyManagement\Analyzer\KeyAnalyzerManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/KeyAnalyzerManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/KeyAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/AlgorithmAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/UsageAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/KeyIdentifierAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/NoneAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/OctAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/HS256KeyAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/HS384KeyAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/HS512KeyAnalyzer.php';

        $container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeyAnalyzerManager'] = $instance = new \Jose\Component\KeyManagement\Analyzer\KeyAnalyzerManager();

        $instance->add(new \Jose\Component\KeyManagement\Analyzer\AlgorithmAnalyzer());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\UsageAnalyzer());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\KeyIdentifierAnalyzer());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\NoneAnalyzer());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\OctAnalyzer());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\HS256KeyAnalyzer());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\HS384KeyAnalyzer());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\HS512KeyAnalyzer());

        return $instance;
    }
}
