<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDg1PPAn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDg1PPAn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDg1PPAn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDg1PPAn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDg1PPAn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dg1PPAn',
    'container.build_id' => '22527a93',
    'container.build_time' => 1630529096,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDg1PPAn');
