<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFKTlVEQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFKTlVEQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFKTlVEQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFKTlVEQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFKTlVEQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FKTlVEQ',
    'container.build_id' => '654db4b0',
    'container.build_time' => 1630573028,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFKTlVEQ');
