<?php

namespace ContainerDg1PPAn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClaimCheckerManagerFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Jose\Bundle\JoseFramework\Services\ClaimCheckerManagerFactory' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\Services\ClaimCheckerManagerFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-bundle/Services/ClaimCheckerManagerFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-checker/ClaimChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-checker/HeaderChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-checker/ExpirationTimeChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-checker/IssuedAtChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-checker/NotBeforeChecker.php';

        $container->services['Jose\\Bundle\\JoseFramework\\Services\\ClaimCheckerManagerFactory'] = $instance = new \Jose\Bundle\JoseFramework\Services\ClaimCheckerManagerFactory(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        $instance->add('exp', new \Jose\Component\Checker\ExpirationTimeChecker());
        $instance->add('iat', new \Jose\Component\Checker\IssuedAtChecker());
        $instance->add('nbf', new \Jose\Component\Checker\NotBeforeChecker());

        return $instance;
    }
}
