<?php

namespace ContainerDg1PPAn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWSVerifierFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Jose\Bundle\JoseFramework\Services\JWSVerifierFactory' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\Services\JWSVerifierFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-bundle/Services/JWSVerifierFactory.php';

        return $container->services['Jose\\Bundle\\JoseFramework\\Services\\JWSVerifierFactory'] = new \Jose\Bundle\JoseFramework\Services\JWSVerifierFactory(($container->services['Jose\\Component\\Core\\AlgorithmManagerFactory'] ?? $container->load('getAlgorithmManagerFactoryService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
