<?php

namespace ContainerWzxoV4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YZ8tOaPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YZ8tOaP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YZ8tOaP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'quizzRepository' => ['privates', 'App\\Repository\\QuizzRepository', 'getQuizzRepositoryService', true],
        ], [
            'quizzRepository' => 'App\\Repository\\QuizzRepository',
        ]);
    }
}
