<?php

namespace ContainerWzxoV4v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompressionMethodManagerFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Jose\Component\Encryption\Compression\CompressionMethodManagerFactory' shared autowired service.
     *
     * @return \Jose\Component\Encryption\Compression\CompressionMethodManagerFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-encryption/Compression/CompressionMethodManagerFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-encryption/Compression/CompressionMethod.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-encryption/Compression/Deflate.php';

        $container->services['Jose\\Component\\Encryption\\Compression\\CompressionMethodManagerFactory'] = $instance = new \Jose\Component\Encryption\Compression\CompressionMethodManagerFactory();

        $instance->add('DEF', new \Jose\Component\Encryption\Compression\Deflate());

        return $instance;
    }
}
