<?php

namespace ContainerDg1PPAn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckerCollectorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Jose\Bundle\JoseFramework\DataCollector\CheckerCollector' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\DataCollector\CheckerCollector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-bundle/DataCollector/Collector.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-bundle/DataCollector/CheckerCollector.php';

        return $container->privates['Jose\\Bundle\\JoseFramework\\DataCollector\\CheckerCollector'] = new \Jose\Bundle\JoseFramework\DataCollector\CheckerCollector(($container->services['Jose\\Bundle\\JoseFramework\\Services\\ClaimCheckerManagerFactory'] ?? $container->load('getClaimCheckerManagerFactoryService')), ($container->services['Jose\\Bundle\\JoseFramework\\Services\\HeaderCheckerManagerFactory'] ?? $container->load('getHeaderCheckerManagerFactoryService')));
    }
}
