<?php

namespace ContainerDg1PPAn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeysetAnalyzerManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Jose\Component\KeyManagement\Analyzer\KeysetAnalyzerManager' shared autowired service.
     *
     * @return \Jose\Component\KeyManagement\Analyzer\KeysetAnalyzerManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/KeysetAnalyzerManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/KeysetAnalyzer.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/MixedKeyTypes.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-key-mgmt/Analyzer/MixedPublicAndPrivateKeys.php';

        $container->services['Jose\\Component\\KeyManagement\\Analyzer\\KeysetAnalyzerManager'] = $instance = new \Jose\Component\KeyManagement\Analyzer\KeysetAnalyzerManager();

        $instance->add(new \Jose\Component\KeyManagement\Analyzer\MixedKeyTypes());
        $instance->add(new \Jose\Component\KeyManagement\Analyzer\MixedPublicAndPrivateKeys());

        return $instance;
    }
}
