<?php

namespace Container5nyig5r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWSCollectorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Jose\Bundle\JoseFramework\DataCollector\JWSCollector' shared autowired service.
     *
     * @return \Jose\Bundle\JoseFramework\DataCollector\JWSCollector
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-bundle/DataCollector/Collector.php';
        include_once \dirname(__DIR__, 4).'/vendor/web-token/jwt-bundle/DataCollector/JWSCollector.php';

        return $container->privates['Jose\\Bundle\\JoseFramework\\DataCollector\\JWSCollector'] = new \Jose\Bundle\JoseFramework\DataCollector\JWSCollector(($container->services['Jose\\Component\\Signature\\Serializer\\JWSSerializerManagerFactory'] ?? $container->getJWSSerializerManagerFactoryService()));
    }
}
