<?php

namespace ContainerFKTlVEQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CategoryController' shared autowired service.
     *
     * @return \App\Controller\CategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CategoryController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CategoryService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CategoryServiceImpl.php';

        $a = ($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService'));
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['App\\Controller\\CategoryController'] = $instance = new \App\Controller\CategoryController(new \App\Service\CategoryServiceImpl($a, $b), $a, $b);

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\CategoryController', $container));

        return $instance;
    }
}
